### ISSUE TITLE
E: Unable to locate package libvpx5

### ISSUE THREAD

**Issue by foremtehan** [mxschmitt/heroku-playwright-buildpack#9]
I just try this pack but i got this errors ;

```
remote:        Get:57 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 mesa-va-drivers amd64 20.2.6-0ubuntu0.20.04.1 [2,618 kB]
remote:        Get:58 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 mesa-vdpau-drivers amd64 20.2.6-0ubuntu0.20.04.1 [2,744 kB]
remote:        Get:59 http://archive.ubuntu.com/ubuntu focal/universe amd64 i965-va-driver amd64 2.4.0-0ubuntu1 [924 kB]
remote:        Get:60 http://archive.ubuntu.com/ubuntu focal/universe amd64 va-driver-all amd64 2.7.0-2 [4,020 B]
remote:        Get:61 http://archive.ubuntu.com/ubuntu focal/main amd64 vdpau-driver-all amd64 1.3-1ubuntu2 [4,596 B]
remote:        Fetched 44.9 MB in 2s (21.0 MB/s)
remote:        Download complete and in download only mode
remote: -----> Fetching .debs for libvpx5
remote:        Reading package lists...
remote:        Building dependency tree...
remote: E: Unable to locate package libvpx5
remote:  !     Push rejected, failed to compile Playwright app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to anobesaz.
remote:
To https://git.heroku.com/anobesaz.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/anobesaz.git'

```

The order of playwright buildpack and nodejs is correct.

**Comment by wrone** [comment]
Hi @foremtehan, I have the same issue, were you able to figure it out?

Error:
![image](https://user-images.githubusercontent.com/9321029/106369625-b54f9f00-635b-11eb-83a8-c10b0761cda7.png)

My settings:
![image](https://user-images.githubusercontent.com/9321029/106369633-c7314200-635b-11eb-88a6-c2b5fa33dcb6.png)

**Comment by wrone** [comment]
I managed to deploy the buildpack. I forked the project (https://github.com/wrone/heroku-playwright-buildpack/blob/master/bin/compile), removed all dependencies and copied only chromium ones from here https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.bionic.

Now I can't execute my script - Error: Cannot find module 'playwright-chromium'.

**Comment by ccaominh** [comment]
I ran into the same error while running on the `heroku-20` stack. Updating from `libvpx5` to `libvpx6` resolved the issue for me: https://github.com/ccaominh/heroku-playwright-buildpack/commit/8c2cb44b5e4ab3a72d70a8f54936690afe8f8280

(Looks like `libvpx5` should work with `heroku-18` though: https://packages.ubuntu.com/search?keywords=libvpx)

**Comment by mxschmitt** [comment]
Hey, maintainer here of the buildpack! Thanks for the investigation. Not sure if I should support both, heroku-18 and heroku-20. We could probably add a check and add it conditionally.

**Comment by mxschmitt** [comment]
Sorry @ccaominh @wrone @foremtehan for the long delay. It should be fixed now.
